# config.yaml
global:
  model: "Qwen/Qwen3-14B-FP8" 
  host: localhost
  port: 8000       
  temperature: 0.0                        
  webshop_url: "http://localhost:3000"

agents:
  my_react_agent:                           # Name of agent, put this name to "python --agent [agent name]""
    type: "react"                           # Type of agent. ["react", "reflexion"]
    workload: "hotpotqa"                    # choices: ["webshop", "hotpotqa", "math", "humaneval"]
    iteration_limit: 30                     # Max number of ReAct step (Thought, Action, Observation)
    fewshot: 5                              # Number of fewshop examples
    samples: 5                              # Number of query samples to test the agent on
    shuffle: true                           # Shuffle the test samples

  my_reflexion_agent:
    type: "reflexion"
    workload: "hotpotqa"                    # choices: ["webshop", "hotpotqa", "math", "humaneval"]
    fewshot: 2                              # Number of fewshop examples
    context_limit: 2000                     # Number of "words" to limit for chat history                  
    iteration_limit: 10                     # Max number of ReAct step between reflections (Thought, Action, Observation)
    reflection_limit: 3                     # Max number of reflection steps
    samples: 5                              # Number of query samples to test the agent on
    shuffle: true                           # Shuffle the test samples
